BEGIN TRANSACTION;
CREATE TABLE account(_id integer not null primary key autoincrement, institution_id integer not null references institution(_id) ON DELETE CASCADE, name text );
INSERT INTO account VALUES(1,1,'Savings');
CREATE TABLE institution(_id integer not null primary key autoincrement, user_id integer not null references user(_id) ON DELETE CASCADE, name text );
INSERT INTO institution VALUES(1,1,'Navy Federal');
CREATE TABLE sqlite_sequence(name,seq);
INSERT INTO sqlite_sequence VALUES('user',1);
INSERT INTO sqlite_sequence VALUES('institution',1);
INSERT INTO sqlite_sequence VALUES('account',1);
INSERT INTO sqlite_sequence VALUES('transaction1',3);
INSERT INTO sqlite_sequence VALUES('tag',2);
INSERT INTO sqlite_sequence VALUES('transaction_tag',1);
CREATE TABLE tag(_id integer not null primary key autoincrement, name text );
INSERT INTO tag VALUES(1,'c');
INSERT INTO tag VALUES(2,'d');
CREATE TABLE transaction1(_id integer not null primary key autoincrement, account_id integer not null references account(_id) ON DELETE CASCADE, date integer not null, name text, display_name text, amount decimal(10,2) );
INSERT INTO transaction1 VALUES(1,1,16865,'a','b',0);
INSERT INTO transaction1 VALUES(2,1,16883,'','',0);
INSERT INTO transaction1 VALUES(3,1,16883,'','',0);
CREATE TABLE transaction_tag(_id integer not null primary key autoincrement, transaction_id integer not null references institution(_id) ON DELETE CASCADE, tag_id integer not null references tag(_id) ON DELETE CASCADE );
INSERT INTO transaction_tag VALUES(1,1,1);
CREATE TABLE user(_id integer not null primary key autoincrement, first_name text, last_name text );
INSERT INTO user VALUES(1,'a','b');
COMMIT;
